name: Auto-Generate README

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write

jobs:
  generate-repo-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Generate README
        run: npm run start
        env:
          GITHUB_TOKEN: ${{ secrets.MANUAL_PAT }}

      - name: Commit and Push Changes
        run: |
          git config --global user.email "ben@sincs.co.uk"
          git config --global user.name "Ben Sinclair"
          git remote add this git@github.com:bensincs/bensincs.git
          git add README.md
          git commit -m "Auto-update README.md"
          git push